# SPDX-FileCopyrightText: 2025 Humanoid Sensing and Perception, Istituto Italiano di Tecnologia
# SPDX-License-Identifier: BSD-3-Clause

name: ergocub_cartesian_control
channels:
  - conda-forge
  - https://repo.prefix.dev/robotology
dependencies:
  - python>=3.10
  - pip
  - yarp==3.12.0
  - proxsuite==0.7.2
  - simde  # header-only dependency required by proxsuite's CMake (FindSimde)
  - idyntree==13.4.2
  - bipedal-locomotion-framework==0.22.0 # for logging
  # For building the Python bindings
  - cmake>=3.16
  - ninja
  - pybind11>=2.10
  - cxx-compiler==1.11.0
  - pip:
      - scikit-build-core>=0.9