/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_SERVICE_ERGOCUBBIMANUALSERVICE_H
#define YARP_THRIFT_GENERATOR_SERVICE_ERGOCUBBIMANUALSERVICE_H

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>
#include <yarp/os/ApplicationNetworkProtocolVersion.h>
#include <yarp/sig/Matrix.h>

class ergoCubBimanualService :
        public yarp::os::Wire
{
public:
    //ProtocolVersion
    virtual yarp::os::ApplicationNetworkProtocolVersion getLocalProtocolVersion();
    virtual yarp::os::ApplicationNetworkProtocolVersion getRemoteProtocolVersion();
    virtual bool checkProtocolVersion();

    // Constructor
    ergoCubBimanualService();

    //Service methods
    virtual bool go_to_pose(const double x, const double y, const double z, const double q_x, const double q_y, const double q_z, const double q_w, const std::string& arm);

    virtual bool go_to_position(const double x, const double y, const double z, const std::string& arm);

    virtual bool rotate_rad(const double angle, const double x, const double y, const double z, const std::string& arm);

    virtual bool rotate_deg(const double angle, const double x, const double y, const double z, const std::string& arm);

    virtual yarp::sig::Matrix get_pose(const std::string& arm);

    virtual bool go_home();

    virtual bool stop();

    // help method
    virtual std::vector<std::string> help(const std::string& functionName = "--all");

    // read from ConnectionReader
    bool read(yarp::os::ConnectionReader& connection) override;
};

#endif // YARP_THRIFT_GENERATOR_SERVICE_ERGOCUBBIMANUALSERVICE_H
